CREATE DATABASE `school_library`;

CREATE TABLE `school_library`.`user` (
  `_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `role` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`_id`),
  UNIQUE INDEX `_id_UNIQUE` (`_id` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC));

CREATE TABLE `school_library`.`teacher` (
  `_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `subject` VARCHAR(45) NULL,
  PRIMARY KEY (`_id`),
  UNIQUE INDEX `_id_UNIQUE` (`_id` ASC),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC),
  CONSTRAINT `teacher_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `school_library`.`user` (`_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE TABLE `school_library`.`student` (
  `_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `teacher_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`_id`),
  UNIQUE INDEX `_id_UNIQUE` (`_id` ASC),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC),
  INDEX `teacher_idx` (`teacher_id ASC`),
  CONSTRAINT `student_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `school_library`.`user` (`_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `student_teacher`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `school_library`.`teacher` (`_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE TABLE `school_library`.`book` (
  `_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `author` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`_id`),
  UNIQUE INDEX `_id_UNIQUE` (`_id` ASC));

CREATE TABLE `school_library`.`library_book` (
  `_id` INT NOT NULL AUTO_INCREMENT,
  `book_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `borrow_date` DATE NULL,
  `return_date` DATE NULL,
  `condition` VARCHAR(1) NULL,
  PRIMARY KEY (`_id`),
  UNIQUE INDEX `_id_UNIQUE` (`_id` ASC),
  INDEX `copy_book_idx` (`book_id` ASC),
  INDEX `copy_user_idx` (`user_id` ASC),
  CONSTRAINT `copy_book`
    FOREIGN KEY (`book_id`)
    REFERENCES `school_library`.`book` (`_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `copy_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `school_library`.`user` (`_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

-- Generated by MySQL Workbench
